[package]
name = "lrtable"
description = "LR grammar table generation"
repository = "https://github.com/softdevteam/grmtools"
version = "0.13.10"
edition = "2021"
readme = "README.md"
license = "Apache-2.0/MIT"
categories = ["parsing"]

[lib]
name = "lrtable"
path = "src/lib/mod.rs"

[dependencies]
cfgrammar = { path="../cfgrammar", version = "0.13", features=["serde"] }

fnv.workspace = true
num-traits.workspace = true
serde = { workspace = true, features = ["derive"], optional = true }
vob = { workspace = true, features = ["serde"] }
sparsevec = { workspace = true, features = ["serde"] }
